=== Noxsara/stargate/stargate-core/src/main/resources/META-INF/stargate.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            xmlns="http://www.sankuai.com/schema/stargate"
            targetNamespace="http://www.sankuai.com/schema/stargate" elementFormDefault="qualified">
    <xsd:element name="QueryPlan">
        <xsd:annotation>
            <xsd:documentation><![CDATA[所有的查询计划]]></xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence maxOccurs="unbounded">
                <xsd:element name="QueryConfig" type="config"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <xsd:complexType name="config">
        <xsd:annotation>
            <xsd:documentation><![CDATA[一个并行查询配置]]></xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="QueryNodes" type="nodes"/>
        </xsd:sequence>
        <xsd:attribute name="bizType" type="xsd:string" use="required"/>
        <xsd:attribute name="description" type="xsd:string"/>
    </xsd:complexType>
    <xsd:complexType name="nodes">
        <xsd:annotation>
            <xsd:documentation><![CDATA[所有查询节点]]></xsd:documentation>
        </xsd:annotation>
        <xsd:sequence maxOccurs="unbounded">
            <xsd:element name="QueryNode" type="node"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="node">
        <xsd:annotation>
            <xsd:documentation><![CDATA[单个查询节点]]></xsd:documentation>
        </xsd:annotation>
        <xsd:sequence>
            <xsd:element name="Name" type="xsd:string"/>
            <xsd:element name="Service" type="xsd:string"/>
            <xsd:element name="Timeout" type="xsd:string"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Noxsara/stargate/stargate-demo/src/main/resources/stargate.xml
<?xml version="1.0" encoding="UTF-8"?>
<QueryPlan xmlns="http://www.sankuai.com/schema/stargate"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.sankuai.com/schema/stargate
           http://www.sankuai.com/schema/stargate.xsd ">

    <QueryConfig bizType="query_list" description="查询列表信息">
        <QueryNodes>
            <QueryNode>
                <Name>query_item</Name>
                <Service>itemQueryService</Service>
                <Timeout>100</Timeout>
            </QueryNode>
            <QueryNode>
                <Name>query_order</Name>
                <Service>orderQueryService</Service>
                <Timeout>500</Timeout>
            </QueryNode>
            <QueryNode>
                <Name>query_user</Name>
                <Service>userQueryService</Service>
                <Timeout>500</Timeout>
            </QueryNode>
        </QueryNodes>
    </QueryConfig>

</QueryPlan>
